<!DOCTYPE html>
<html lang="es">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Asincronismo en JS</title>
</head>

<body>
  <h1>Asincronia en JavaScript</h1>
  <h2>Async - Await</h2>

  <p>Estas son las funciones asincronas, como su nombre lo dice son funciones que van a esperar a que se tenga una
    respuesta o una solucion a su ejecucion para poder seguir ejecutando el proceso que se este manejando en el momento,
    no vienen a reemplar las promesas si no ayudarla y trabajar en conjunto</p>

  <script>
    function cuadradoPromise(value) {
      if (typeof value !== "number") {
        return Promise.reject(`El valor ${value} ingresado no es un numero`);
      };
      return new Promise((resolve, reject) => {
        setTimeout(() => {
          resolve({
            value: value,
            result: value * value,
          });
        }, 0 | Math.random() * 1000);
      });
    };

    async function funcionAsincronaDeclarada() {
      try {
        console.log("Inicio de Async Function");

        let obj = await cuadradoPromise(0);
        console.log(`Async Function: ${obj.value}, ${obj.result}`);

        obj = await cuadradoPromise(1);
        console.log(`Async Function: ${obj.value}, ${obj.result}`);

        obj = await cuadradoPromise(2);
        console.log(`Async Function: ${obj.value}, ${obj.result}`);

        obj = await cuadradoPromise(3);
        console.log(`Async Function: ${obj.value}, ${obj.result}`);

        obj = await cuadradoPromise(4);
        console.log(`Async Function: ${obj.value}, ${obj.result}`);

        obj = await cuadradoPromise(5);
        console.log(`Async Function: ${obj.value}, ${obj.result}`);
        console.log("Fin Async Function");
        funcionAsincronaExpresada();
      } catch (error) {
        console.error(error)
      }
    };

    funcionAsincronaDeclarada();

    const funcionAsincronaExpresada = async () => {
      try {
        console.log("Inicio de Async Function Expresada");

        let obj = await cuadradoPromise(6);
        console.log(`Async Function: ${obj.value}, ${obj.result}`);

        obj = await cuadradoPromise(7);
        console.log(`Async Function: ${obj.value}, ${obj.result}`);

        obj = await cuadradoPromise(8);
        console.log(`Async Function: ${obj.value}, ${obj.result}`);

        obj = await cuadradoPromise(9);
        console.log(`Async Function: ${obj.value}, ${obj.result}`);

        obj = await cuadradoPromise(10);
        console.log(`Async Function: ${obj.value}, ${obj.result}`);

        obj = await cuadradoPromise(11);
        console.log(`Async Function: ${obj.value}, ${obj.result}`);
        console.log("Fin Async Function");
      } catch (error) {
        console.error(error)
      }
    };



  </script>
</body>

</html>